### ISSUE TITLE
Is it possible to make machine overriding user, and user overriding role?

### ISSUE THREAD

**Issue by Narice** [HugoReeves/nix-home#1]
Hello,
I'm really new to nix so this might be a dumb question but would it be possible in the home.nix to have the machine override the config of the user and make the user override the role config?
I searched how to do this with nix modules and found out about the [input design pattern](https://nixos.org/nixos/nix-pills/inputs-design-pattern.html). Do you think it could be doable with this pattern?
Also, I've seen your use of lib.attrsets.recursiveUpdate [here](https://github.com/HugoReeves/nix-home/blob/master/role/bspwm-workstation/index.nix). Is it applicable to what I want to achieve? Can't really find any documentation on it so I'm a bit stuck.
Thank you and sorry again if this is a newbie kind of question :sweat_smile:

**Comment by HugoReeves** [comment]
@Narice You may have noticed the lack of commits to this repo recently. I've actually restructured the entire repo to use the options system. I'm currently drafting a blog post to explain the new system and will publish the corresponding repo at the same time. The use of recursiveUpdate allows for a set of default options to be overridden based on the machine/host specific requirements. Using recursive update correctly you can achieve what you want but it will likely make your code more complex and difficult to understand. In the new system, options are used to achieve this and I think it's a much cleaner solution. I'll ping this issue once the blog post is complete.

**Comment by Narice** [comment]
Oh woaw nice!
I'll be waiting for your blog post then before doing anything, I think my comment was the only pitfall I found to your way of doing things so I'm really pleased that this issue will be resolved in your next post!

I actively want to switch step by step from pacman to nix, and home-manager is a really good first step as you suggested on [this](https://www.reddit.com/r/NixOS/comments/gae1rv/transitioning_without_having_to_copy_all_my/) reddit thread. Thank you very much for the work your putting into this repo, it's really helpful.

Also, you could maybe explain in you post how you use git-crypt and nix modules to have private informations in otherwise public repositories, your way of doing things seems really useful but I don't really know how to replicate it, however that might be a newbie question and also not at all the topic of your post so that's just a dumb suggestion in case it makes sense to include this in your post.

**Comment by Narice** [comment]
I was planning on doing something for my setup so I reconsidered your file structure. do you have any updates on the post?
btw, I entirely switched to nixos and it's a blast!

**Comment by HugoReeves** [comment]
@Narice Sorry, this has been extremely slow from me. I've just publishes the replacement system I'm not using. It's linked in the README here but you can find it at [hugoreeves/elemental](https://github.com/hugoreeves/elemental). Hopefully some of the source configs will give you an idea of overriding values. Specifically, look at how the machine configuration sets values for backup using restic, but the backups are enabled by the role configuration.

**Comment by Narice** [comment]
Thanks for the response! I didn't spot it before today, thanks for the link ^^
I'm actually getting invested in [divnix/devos](https://github.com/divnix/devos) and their file structure is extremely good, I highly recommend it for people reading this in the future.
There are actually some similarities between the structure they have and yours, it's really cool to see!
